apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-demo
  namespace: flux-system
spec:
  interval: 5m
  path: ./helm/gitops-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-demo-repo
