apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gitops-demo
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
